/*
* generated by Xtext
*/
package org.softlang.megal.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.softlang.megal.services.MegaLGrammarAccess;

public class MegaLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MegaLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_ML_COMMENT", "RULE_SL_COMMENT", "RULE_WS");
	}
	
	@Override
	protected org.softlang.megal.parser.antlr.internal.InternalMegaLParser createParser(XtextTokenStream stream) {
		return new org.softlang.megal.parser.antlr.internal.InternalMegaLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public MegaLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MegaLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
