/*
 * generated by Xtext
 */
package org.softlang.megal.validation

import org.eclipse.xtext.validation.Check
import org.softlang.megal.megaL.ED
import org.softlang.megal.megaL.MegaLPackage
import org.softlang.megal.megaL.ETD

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class MegaLValidator extends AbstractMegaLValidator {

	@Check
	def checkSemanticsExisting(ETD it) {
		warning('No implementation for ' + name, MegaLPackage.Literals.ETD__NAME)
	}

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
}
