/*
 * generated by Xtext
 */
package org.softlang.megal.language.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.softlang.megal.language.services.MegalGrammarAccess;

public class MegalParser extends AbstractContentAssistParser {
	
	@Inject
	private MegalGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.softlang.megal.language.ui.contentassist.antlr.internal.InternalMegalParser createParser() {
		org.softlang.megal.language.ui.contentassist.antlr.internal.InternalMegalParser result = new org.softlang.megal.language.ui.contentassist.antlr.internal.InternalMegalParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getMegalFileAccess().getAlternatives_3(), "rule__MegalFile__Alternatives_3");
					put(grammarAccess.getMegalEntityTypeAccess().getAlternatives_2(), "rule__MegalEntityType__Alternatives_2");
					put(grammarAccess.getMegalRelationshipTypeAccess().getAlternatives_5(), "rule__MegalRelationshipType__Alternatives_5");
					put(grammarAccess.getMegalRelationshipTypeAccess().getAlternatives_9(), "rule__MegalRelationshipType__Alternatives_9");
					put(grammarAccess.getQueryDefEntryAccess().getAlternatives(), "rule__QueryDefEntry__Alternatives");
					put(grammarAccess.getQueryRefEntryAccess().getAlternatives(), "rule__QueryRefEntry__Alternatives");
					put(grammarAccess.getMegalFileAccess().getGroup(), "rule__MegalFile__Group__0");
					put(grammarAccess.getMegalFileAccess().getGroup_3_0(), "rule__MegalFile__Group_3_0__0");
					put(grammarAccess.getMegalAnnotationAccess().getGroup(), "rule__MegalAnnotation__Group__0");
					put(grammarAccess.getMegalLinkAccess().getGroup(), "rule__MegalLink__Group__0");
					put(grammarAccess.getMegalLinkAccess().getGroup_2(), "rule__MegalLink__Group_2__0");
					put(grammarAccess.getMegalEntityTypeAccess().getGroup(), "rule__MegalEntityType__Group__0");
					put(grammarAccess.getMegalEntityTypeAccess().getGroup_2_0(), "rule__MegalEntityType__Group_2_0__0");
					put(grammarAccess.getMegalEntityTypeAccess().getGroup_2_1(), "rule__MegalEntityType__Group_2_1__0");
					put(grammarAccess.getMegalRelationshipTypeAccess().getGroup(), "rule__MegalRelationshipType__Group__0");
					put(grammarAccess.getMegalRelationshipTypeAccess().getGroup_4(), "rule__MegalRelationshipType__Group_4__0");
					put(grammarAccess.getMegalRelationshipTypeAccess().getGroup_4_2(), "rule__MegalRelationshipType__Group_4_2__0");
					put(grammarAccess.getMegalRelationshipTypeAccess().getGroup_8(), "rule__MegalRelationshipType__Group_8__0");
					put(grammarAccess.getMegalRelationshipTypeAccess().getGroup_8_2(), "rule__MegalRelationshipType__Group_8_2__0");
					put(grammarAccess.getMegalEntityAccess().getGroup(), "rule__MegalEntity__Group__0");
					put(grammarAccess.getMegalEntityAccess().getGroup_4(), "rule__MegalEntity__Group_4__0");
					put(grammarAccess.getMegalEntityAccess().getGroup_4_2(), "rule__MegalEntity__Group_4_2__0");
					put(grammarAccess.getMegalRelationshipAccess().getGroup(), "rule__MegalRelationship__Group__0");
					put(grammarAccess.getMegalPairAccess().getGroup(), "rule__MegalPair__Group__0");
					put(grammarAccess.getSelectionAccess().getGroup(), "rule__Selection__Group__0");
					put(grammarAccess.getSelectionAccess().getGroup_1(), "rule__Selection__Group_1__0");
					put(grammarAccess.getSelectionAccess().getGroup_2(), "rule__Selection__Group_2__0");
					put(grammarAccess.getQueryStatementAccess().getGroup(), "rule__QueryStatement__Group__0");
					put(grammarAccess.getQueryParamAccess().getGroup(), "rule__QueryParam__Group__0");
					put(grammarAccess.getQueryParamAccess().getGroup_1(), "rule__QueryParam__Group_1__0");
					put(grammarAccess.getQueryPosAccess().getGroup(), "rule__QueryPos__Group__0");
					put(grammarAccess.getMegalFileAccess().getAnnotationsAssignment_0(), "rule__MegalFile__AnnotationsAssignment_0");
					put(grammarAccess.getMegalFileAccess().getNameAssignment_2(), "rule__MegalFile__NameAssignment_2");
					put(grammarAccess.getMegalFileAccess().getImportsAssignment_3_0_1(), "rule__MegalFile__ImportsAssignment_3_0_1");
					put(grammarAccess.getMegalFileAccess().getDeclarationsAssignment_3_1(), "rule__MegalFile__DeclarationsAssignment_3_1");
					put(grammarAccess.getMegalFileAccess().getDeclarationsAssignment_3_2(), "rule__MegalFile__DeclarationsAssignment_3_2");
					put(grammarAccess.getMegalFileAccess().getDeclarationsAssignment_3_3(), "rule__MegalFile__DeclarationsAssignment_3_3");
					put(grammarAccess.getMegalFileAccess().getDeclarationsAssignment_3_4(), "rule__MegalFile__DeclarationsAssignment_3_4");
					put(grammarAccess.getMegalFileAccess().getDeclarationsAssignment_3_5(), "rule__MegalFile__DeclarationsAssignment_3_5");
					put(grammarAccess.getMegalFileAccess().getBindingsAssignment_3_6(), "rule__MegalFile__BindingsAssignment_3_6");
					put(grammarAccess.getMegalAnnotationAccess().getKeyAssignment_0(), "rule__MegalAnnotation__KeyAssignment_0");
					put(grammarAccess.getMegalAnnotationAccess().getSelectionAssignment_1(), "rule__MegalAnnotation__SelectionAssignment_1");
					put(grammarAccess.getMegalLinkAccess().getAnnotationsAssignment_0(), "rule__MegalLink__AnnotationsAssignment_0");
					put(grammarAccess.getMegalLinkAccess().getLinkAssignment_1(), "rule__MegalLink__LinkAssignment_1");
					put(grammarAccess.getMegalLinkAccess().getFirstAssignment_2_1(), "rule__MegalLink__FirstAssignment_2_1");
					put(grammarAccess.getMegalLinkAccess().getSecondAssignment_2_4(), "rule__MegalLink__SecondAssignment_2_4");
					put(grammarAccess.getMegalLinkAccess().getToAssignment_4(), "rule__MegalLink__ToAssignment_4");
					put(grammarAccess.getMegalEntityTypeAccess().getAnnotationsAssignment_0(), "rule__MegalEntityType__AnnotationsAssignment_0");
					put(grammarAccess.getMegalEntityTypeAccess().getNameAssignment_1(), "rule__MegalEntityType__NameAssignment_1");
					put(grammarAccess.getMegalEntityTypeAccess().getSupertypeAssignment_2_0_1(), "rule__MegalEntityType__SupertypeAssignment_2_0_1");
					put(grammarAccess.getMegalRelationshipTypeAccess().getAnnotationsAssignment_0(), "rule__MegalRelationshipType__AnnotationsAssignment_0");
					put(grammarAccess.getMegalRelationshipTypeAccess().getNameAssignment_1(), "rule__MegalRelationshipType__NameAssignment_1");
					put(grammarAccess.getMegalRelationshipTypeAccess().getLeftAssignment_3(), "rule__MegalRelationshipType__LeftAssignment_3");
					put(grammarAccess.getMegalRelationshipTypeAccess().getLeftParamsAssignment_4_1(), "rule__MegalRelationshipType__LeftParamsAssignment_4_1");
					put(grammarAccess.getMegalRelationshipTypeAccess().getLeftParamsAssignment_4_2_1(), "rule__MegalRelationshipType__LeftParamsAssignment_4_2_1");
					put(grammarAccess.getMegalRelationshipTypeAccess().getLeftBothAssignment_5_0(), "rule__MegalRelationshipType__LeftBothAssignment_5_0");
					put(grammarAccess.getMegalRelationshipTypeAccess().getLeftManyAssignment_5_1(), "rule__MegalRelationshipType__LeftManyAssignment_5_1");
					put(grammarAccess.getMegalRelationshipTypeAccess().getRightAssignment_7(), "rule__MegalRelationshipType__RightAssignment_7");
					put(grammarAccess.getMegalRelationshipTypeAccess().getRightParamsAssignment_8_1(), "rule__MegalRelationshipType__RightParamsAssignment_8_1");
					put(grammarAccess.getMegalRelationshipTypeAccess().getRightParamsAssignment_8_2_1(), "rule__MegalRelationshipType__RightParamsAssignment_8_2_1");
					put(grammarAccess.getMegalRelationshipTypeAccess().getRightBothAssignment_9_0(), "rule__MegalRelationshipType__RightBothAssignment_9_0");
					put(grammarAccess.getMegalRelationshipTypeAccess().getRightManyAssignment_9_1(), "rule__MegalRelationshipType__RightManyAssignment_9_1");
					put(grammarAccess.getMegalEntityAccess().getAnnotationsAssignment_0(), "rule__MegalEntity__AnnotationsAssignment_0");
					put(grammarAccess.getMegalEntityAccess().getNameAssignment_1(), "rule__MegalEntity__NameAssignment_1");
					put(grammarAccess.getMegalEntityAccess().getTypeAssignment_3(), "rule__MegalEntity__TypeAssignment_3");
					put(grammarAccess.getMegalEntityAccess().getParamsAssignment_4_1(), "rule__MegalEntity__ParamsAssignment_4_1");
					put(grammarAccess.getMegalEntityAccess().getParamsAssignment_4_2_1(), "rule__MegalEntity__ParamsAssignment_4_2_1");
					put(grammarAccess.getMegalEntityAccess().getManyAssignment_5(), "rule__MegalEntity__ManyAssignment_5");
					put(grammarAccess.getMegalRelationshipAccess().getAnnotationsAssignment_0(), "rule__MegalRelationship__AnnotationsAssignment_0");
					put(grammarAccess.getMegalRelationshipAccess().getLeftAssignment_1(), "rule__MegalRelationship__LeftAssignment_1");
					put(grammarAccess.getMegalRelationshipAccess().getTypeAssignment_2(), "rule__MegalRelationship__TypeAssignment_2");
					put(grammarAccess.getMegalRelationshipAccess().getRightAssignment_3(), "rule__MegalRelationship__RightAssignment_3");
					put(grammarAccess.getMegalPairAccess().getAnnotationsAssignment_0(), "rule__MegalPair__AnnotationsAssignment_0");
					put(grammarAccess.getMegalPairAccess().getSetAssignment_1(), "rule__MegalPair__SetAssignment_1");
					put(grammarAccess.getMegalPairAccess().getFirstAssignment_3(), "rule__MegalPair__FirstAssignment_3");
					put(grammarAccess.getMegalPairAccess().getSecondAssignment_6(), "rule__MegalPair__SecondAssignment_6");
					put(grammarAccess.getSelectionAccess().getSelectAssignment_0(), "rule__Selection__SelectAssignment_0");
					put(grammarAccess.getSelectionAccess().getSelectAssignment_1_1(), "rule__Selection__SelectAssignment_1_1");
					put(grammarAccess.getSelectionAccess().getQueryAssignment_2_2(), "rule__Selection__QueryAssignment_2_2");
					put(grammarAccess.getQueryStatementAccess().getSubjectAssignment_0(), "rule__QueryStatement__SubjectAssignment_0");
					put(grammarAccess.getQueryStatementAccess().getPredicateAssignment_1(), "rule__QueryStatement__PredicateAssignment_1");
					put(grammarAccess.getQueryStatementAccess().getObjectAssignment_2(), "rule__QueryStatement__ObjectAssignment_2");
					put(grammarAccess.getQueryParamAccess().getNameAssignment_0(), "rule__QueryParam__NameAssignment_0");
					put(grammarAccess.getQueryParamAccess().getTypeAssignment_1_1(), "rule__QueryParam__TypeAssignment_1_1");
					put(grammarAccess.getQueryReferenceAccess().getRefAssignment(), "rule__QueryReference__RefAssignment");
					put(grammarAccess.getQueryStringAccess().getValueAssignment(), "rule__QueryString__ValueAssignment");
					put(grammarAccess.getQueryEntityAccess().getEntityAssignment(), "rule__QueryEntity__EntityAssignment");
					put(grammarAccess.getQueryPosAccess().getValueAssignment_1(), "rule__QueryPos__ValueAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.softlang.megal.language.ui.contentassist.antlr.internal.InternalMegalParser typedParser = (org.softlang.megal.language.ui.contentassist.antlr.internal.InternalMegalParser) parser;
			typedParser.entryRuleMegalFile();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_COMMENT" };
	}
	
	public MegalGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MegalGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
