/*
 * generated by Xtext
 */
package org.softlang.megal.language.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.softlang.megal.language.services.MegalGrammarAccess;

public class MegalParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MegalGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_COMMENT");
	}
	
	@Override
	protected org.softlang.megal.language.parser.antlr.internal.InternalMegalParser createParser(XtextTokenStream stream) {
		return new org.softlang.megal.language.parser.antlr.internal.InternalMegalParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "MegalFile";
	}
	
	public MegalGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MegalGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
