/*
* generated by Xtext
*/
package org.softlang.megal.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MegaLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class MegaLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MegaL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cModelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cAlternatives_2.eContents().get(0);
		private final Keyword cImportKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Assignment cImportsAssignment_2_0_1 = (Assignment)cGroup_2_0.eContents().get(1);
		private final CrossReference cImportsMegaLCrossReference_2_0_1_0 = (CrossReference)cImportsAssignment_2_0_1.eContents().get(0);
		private final RuleCall cImportsMegaLIDTerminalRuleCall_2_0_1_0_1 = (RuleCall)cImportsMegaLCrossReference_2_0_1_0.eContents().get(1);
		private final Assignment cEtdAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cEtdETDParserRuleCall_2_1_0 = (RuleCall)cEtdAssignment_2_1.eContents().get(0);
		private final Assignment cRtdAssignment_2_2 = (Assignment)cAlternatives_2.eContents().get(2);
		private final RuleCall cRtdRTDParserRuleCall_2_2_0 = (RuleCall)cRtdAssignment_2_2.eContents().get(0);
		private final Assignment cEdAssignment_2_3 = (Assignment)cAlternatives_2.eContents().get(3);
		private final RuleCall cEdEDParserRuleCall_2_3_0 = (RuleCall)cEdAssignment_2_3.eContents().get(0);
		private final Assignment cRdAssignment_2_4 = (Assignment)cAlternatives_2.eContents().get(4);
		private final RuleCall cRdRDParserRuleCall_2_4_0 = (RuleCall)cRdAssignment_2_4.eContents().get(0);
		
		//MegaL:
		//	"model" name=QualifiedID ("import" imports+=[MegaL] | etd+=ETD | rtd+=RTD | ed+=ED | rd+=RD)*;
		public ParserRule getRule() { return rule; }

		//"model" name=QualifiedID ("import" imports+=[MegaL] | etd+=ETD | rtd+=RTD | ed+=ED | rd+=RD)*
		public Group getGroup() { return cGroup; }

		//"model"
		public Keyword getModelKeyword_0() { return cModelKeyword_0; }

		//name=QualifiedID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//QualifiedID
		public RuleCall getNameQualifiedIDParserRuleCall_1_0() { return cNameQualifiedIDParserRuleCall_1_0; }

		//("import" imports+=[MegaL] | etd+=ETD | rtd+=RTD | ed+=ED | rd+=RD)*
		public Alternatives getAlternatives_2() { return cAlternatives_2; }

		//"import" imports+=[MegaL]
		public Group getGroup_2_0() { return cGroup_2_0; }

		//"import"
		public Keyword getImportKeyword_2_0_0() { return cImportKeyword_2_0_0; }

		//imports+=[MegaL]
		public Assignment getImportsAssignment_2_0_1() { return cImportsAssignment_2_0_1; }

		//[MegaL]
		public CrossReference getImportsMegaLCrossReference_2_0_1_0() { return cImportsMegaLCrossReference_2_0_1_0; }

		//ID
		public RuleCall getImportsMegaLIDTerminalRuleCall_2_0_1_0_1() { return cImportsMegaLIDTerminalRuleCall_2_0_1_0_1; }

		//etd+=ETD
		public Assignment getEtdAssignment_2_1() { return cEtdAssignment_2_1; }

		//ETD
		public RuleCall getEtdETDParserRuleCall_2_1_0() { return cEtdETDParserRuleCall_2_1_0; }

		//rtd+=RTD
		public Assignment getRtdAssignment_2_2() { return cRtdAssignment_2_2; }

		//RTD
		public RuleCall getRtdRTDParserRuleCall_2_2_0() { return cRtdRTDParserRuleCall_2_2_0; }

		//ed+=ED
		public Assignment getEdAssignment_2_3() { return cEdAssignment_2_3; }

		//ED
		public RuleCall getEdEDParserRuleCall_2_3_0() { return cEdEDParserRuleCall_2_3_0; }

		//rd+=RD
		public Assignment getRdAssignment_2_4() { return cRdAssignment_2_4; }

		//RD
		public RuleCall getRdRDParserRuleCall_2_4_0() { return cRdRDParserRuleCall_2_4_0; }
	}

	public class ETDRElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ETDR");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cETDEntityParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cETDDeclaredParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ETDR:
		//	ETDEntity | ETDDeclared;
		public ParserRule getRule() { return rule; }

		//ETDEntity | ETDDeclared
		public Alternatives getAlternatives() { return cAlternatives; }

		//ETDEntity
		public RuleCall getETDEntityParserRuleCall_0() { return cETDEntityParserRuleCall_0; }

		//ETDDeclared
		public RuleCall getETDDeclaredParserRuleCall_1() { return cETDDeclaredParserRuleCall_1; }
	}

	public class ETDEntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ETDEntity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cETDEntityAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEntityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//ETDEntity:
		//	{ETDEntity} "Entity";
		public ParserRule getRule() { return rule; }

		//{ETDEntity} "Entity"
		public Group getGroup() { return cGroup; }

		//{ETDEntity}
		public Action getETDEntityAction_0() { return cETDEntityAction_0; }

		//"Entity"
		public Keyword getEntityKeyword_1() { return cEntityKeyword_1; }
	}

	public class ETDDeclaredElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ETDDeclared");
		private final Assignment cReferenceAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cReferenceETDCrossReference_0 = (CrossReference)cReferenceAssignment.eContents().get(0);
		private final RuleCall cReferenceETDIDTerminalRuleCall_0_1 = (RuleCall)cReferenceETDCrossReference_0.eContents().get(1);
		
		//ETDDeclared:
		//	reference=[ETD];
		public ParserRule getRule() { return rule; }

		//reference=[ETD]
		public Assignment getReferenceAssignment() { return cReferenceAssignment; }

		//[ETD]
		public CrossReference getReferenceETDCrossReference_0() { return cReferenceETDCrossReference_0; }

		//ID
		public RuleCall getReferenceETDIDTerminalRuleCall_0_1() { return cReferenceETDIDTerminalRuleCall_0_1; }
	}

	public class ETDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ETD");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLessThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSupertypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSupertypeETDRParserRuleCall_2_0 = (RuleCall)cSupertypeAssignment_2.eContents().get(0);
		
		//ETD:
		//	name=ID "<" supertype=ETDR;
		public ParserRule getRule() { return rule; }

		//name=ID "<" supertype=ETDR
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//"<"
		public Keyword getLessThanSignKeyword_1() { return cLessThanSignKeyword_1; }

		//supertype=ETDR
		public Assignment getSupertypeAssignment_2() { return cSupertypeAssignment_2; }

		//ETDR
		public RuleCall getSupertypeETDRParserRuleCall_2_0() { return cSupertypeETDRParserRuleCall_2_0; }
	}

	public class RTDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RTD");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLessThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDomainAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDomainETDRParserRuleCall_2_0 = (RuleCall)cDomainAssignment_2.eContents().get(0);
		private final Keyword cAsteriskKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCoDomainAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCoDomainETDRParserRuleCall_4_0 = (RuleCall)cCoDomainAssignment_4.eContents().get(0);
		
		//RTD:
		//	name=ID "<" domain=ETDR "*" coDomain=ETDR;
		public ParserRule getRule() { return rule; }

		//name=ID "<" domain=ETDR "*" coDomain=ETDR
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//"<"
		public Keyword getLessThanSignKeyword_1() { return cLessThanSignKeyword_1; }

		//domain=ETDR
		public Assignment getDomainAssignment_2() { return cDomainAssignment_2; }

		//ETDR
		public RuleCall getDomainETDRParserRuleCall_2_0() { return cDomainETDRParserRuleCall_2_0; }

		//"*"
		public Keyword getAsteriskKeyword_3() { return cAsteriskKeyword_3; }

		//coDomain=ETDR
		public Assignment getCoDomainAssignment_4() { return cCoDomainAssignment_4; }

		//ETDR
		public RuleCall getCoDomainETDRParserRuleCall_4_0() { return cCoDomainETDRParserRuleCall_4_0; }
	}

	public class EDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ED");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeETDRParserRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		
		//ED:
		//	name=ID ":" type=ETDR;
		public ParserRule getRule() { return rule; }

		//name=ID ":" type=ETDR
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//type=ETDR
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }

		//ETDR
		public RuleCall getTypeETDRParserRuleCall_2_0() { return cTypeETDRParserRuleCall_2_0; }
	}

	public class RDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RD");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSourceAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cSourceEDCrossReference_0_0 = (CrossReference)cSourceAssignment_0.eContents().get(0);
		private final RuleCall cSourceEDIDTerminalRuleCall_0_0_1 = (RuleCall)cSourceEDCrossReference_0_0.eContents().get(1);
		private final Assignment cRelAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cRelRTDCrossReference_1_0 = (CrossReference)cRelAssignment_1.eContents().get(0);
		private final RuleCall cRelRTDIDTerminalRuleCall_1_0_1 = (RuleCall)cRelRTDCrossReference_1_0.eContents().get(1);
		private final Assignment cTargetAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTargetEDCrossReference_2_0 = (CrossReference)cTargetAssignment_2.eContents().get(0);
		private final RuleCall cTargetEDIDTerminalRuleCall_2_0_1 = (RuleCall)cTargetEDCrossReference_2_0.eContents().get(1);
		
		//RD:
		//	source=[ED] rel=[RTD] target=[ED];
		public ParserRule getRule() { return rule; }

		//source=[ED] rel=[RTD] target=[ED]
		public Group getGroup() { return cGroup; }

		//source=[ED]
		public Assignment getSourceAssignment_0() { return cSourceAssignment_0; }

		//[ED]
		public CrossReference getSourceEDCrossReference_0_0() { return cSourceEDCrossReference_0_0; }

		//ID
		public RuleCall getSourceEDIDTerminalRuleCall_0_0_1() { return cSourceEDIDTerminalRuleCall_0_0_1; }

		//rel=[RTD]
		public Assignment getRelAssignment_1() { return cRelAssignment_1; }

		//[RTD]
		public CrossReference getRelRTDCrossReference_1_0() { return cRelRTDCrossReference_1_0; }

		//ID
		public RuleCall getRelRTDIDTerminalRuleCall_1_0_1() { return cRelRTDIDTerminalRuleCall_1_0_1; }

		//target=[ED]
		public Assignment getTargetAssignment_2() { return cTargetAssignment_2; }

		//[ED]
		public CrossReference getTargetEDCrossReference_2_0() { return cTargetEDCrossReference_2_0; }

		//ID
		public RuleCall getTargetEDIDTerminalRuleCall_2_0_1() { return cTargetEDIDTerminalRuleCall_2_0_1; }
	}

	public class QualifiedIDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedID");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedID:
		//	ID ("." ID)*;
		public ParserRule getRule() { return rule; }

		//ID ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	
	
	private MegaLElements pMegaL;
	private ETDRElements pETDR;
	private ETDEntityElements pETDEntity;
	private ETDDeclaredElements pETDDeclared;
	private ETDElements pETD;
	private RTDElements pRTD;
	private EDElements pED;
	private RDElements pRD;
	private QualifiedIDElements pQualifiedID;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public MegaLGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.softlang.megal.MegaL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//MegaL:
	//	"model" name=QualifiedID ("import" imports+=[MegaL] | etd+=ETD | rtd+=RTD | ed+=ED | rd+=RD)*;
	public MegaLElements getMegaLAccess() {
		return (pMegaL != null) ? pMegaL : (pMegaL = new MegaLElements());
	}
	
	public ParserRule getMegaLRule() {
		return getMegaLAccess().getRule();
	}

	//ETDR:
	//	ETDEntity | ETDDeclared;
	public ETDRElements getETDRAccess() {
		return (pETDR != null) ? pETDR : (pETDR = new ETDRElements());
	}
	
	public ParserRule getETDRRule() {
		return getETDRAccess().getRule();
	}

	//ETDEntity:
	//	{ETDEntity} "Entity";
	public ETDEntityElements getETDEntityAccess() {
		return (pETDEntity != null) ? pETDEntity : (pETDEntity = new ETDEntityElements());
	}
	
	public ParserRule getETDEntityRule() {
		return getETDEntityAccess().getRule();
	}

	//ETDDeclared:
	//	reference=[ETD];
	public ETDDeclaredElements getETDDeclaredAccess() {
		return (pETDDeclared != null) ? pETDDeclared : (pETDDeclared = new ETDDeclaredElements());
	}
	
	public ParserRule getETDDeclaredRule() {
		return getETDDeclaredAccess().getRule();
	}

	//ETD:
	//	name=ID "<" supertype=ETDR;
	public ETDElements getETDAccess() {
		return (pETD != null) ? pETD : (pETD = new ETDElements());
	}
	
	public ParserRule getETDRule() {
		return getETDAccess().getRule();
	}

	//RTD:
	//	name=ID "<" domain=ETDR "*" coDomain=ETDR;
	public RTDElements getRTDAccess() {
		return (pRTD != null) ? pRTD : (pRTD = new RTDElements());
	}
	
	public ParserRule getRTDRule() {
		return getRTDAccess().getRule();
	}

	//ED:
	//	name=ID ":" type=ETDR;
	public EDElements getEDAccess() {
		return (pED != null) ? pED : (pED = new EDElements());
	}
	
	public ParserRule getEDRule() {
		return getEDAccess().getRule();
	}

	//RD:
	//	source=[ED] rel=[RTD] target=[ED];
	public RDElements getRDAccess() {
		return (pRD != null) ? pRD : (pRD = new RDElements());
	}
	
	public ParserRule getRDRule() {
		return getRDAccess().getRule();
	}

	//QualifiedID:
	//	ID ("." ID)*;
	public QualifiedIDElements getQualifiedIDAccess() {
		return (pQualifiedID != null) ? pQualifiedID : (pQualifiedID = new QualifiedIDElements());
	}
	
	public ParserRule getQualifiedIDRule() {
		return getQualifiedIDAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
