/*
 * generated by Xtext
 */
package org.softlang.megal;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MegaLRuntimeModule extends org.softlang.megal.AbstractMegaLRuntimeModule {

}
