/*
* generated by Xtext
*/
package org.softlang.megal;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MegaLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.softlang.megal.ui.internal.MegaLActivator.getInstance().getInjector("org.softlang.megal.MegaL");
	}
	
}
