/*
 * generated by Xtext
 */
package org.softlang.megal.language.ui.contentassist

import org.softlang.megal.language.ui.contentassist.AbstractMegalProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MegalProposalProvider extends AbstractMegalProposalProvider {
}
